# Site settings
title:       "Учимся вебдеву"
header_title: "Учимся вебдеву"
author:      Ignat
description: "Дневник про изучение веб-разработки."
baseurl:     ""
url:         "http://dev_journal.ignat.co"
date_format: "%-d.%m.%Y"

# Google services
google_analytics: "UA-1360700-62"
google_verification: ""

# Facebook

# Optional features
animated:             false
show_related_posts:   false
show_post_footer:    false
show_social_icons: false
ajaxify_contact_form: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: "uchimsia-vebdevu"

# Social icons
github_username: buyfn
telegram_username: dev_journal
bitbucket_username:
stackoverflow_id:
twitter_username: buyfn
google_plus_id:
linkedin_username:
facebook_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
instagram_username:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
highlighter: none
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    "/:title/"
paginate:     10
sass:
  compressed: true

# Gems
gems: [jekyll-paginate]
